Update funkeycia

diff --git a/scripts/funkeycia b/scripts/funkeycia
--- a/scripts/funkeycia
+++ b/scripts/funkeycia
@@ -5,6 +5,7 @@
 dir_bin=~/.bin
 dir_tmp=~/src/tmp
 dir_games=~/Documents/3ds/dependencies/cia/games
+dir_updates=~/Documents/3ds/dependencies/cia/updates
 dir_locales=~/Documents/3ds/dependencies/locales
 
 # Define binaries
@@ -17,21 +18,52 @@ cp $bin_make_cdn_cia $dir_tmp/;
 echo "";
 echo "https://3ds.titlekeys.com/";
 echo "";
-echo -n "Enter Title: "
-read title;
-echo -n "Enter encrypted title key: ";
-read key;
-echo -n "Rename title: "
-read title_rename;
-echo "";
+echo "***** FunkeyCIA Menu *****";
+echo "[1] Download game";
+echo "[2] Download update/patch";
+echo -n "Select your choice: ";
+read choice;
+case $choice in
+  1)
+  echo "";
+  echo -n "Enter Title: "
+  read title;
+  echo -n "Enter encrypted title key: ";
+  read key;
+  echo -n "Rename title: "
+  read title_rename;
+  echo "";
 
-python $bin_funkeycia -title $title -key $key;
+  python $bin_funkeycia -title $title -key $key;
 
-echo "Moving game file...";
-mv -v $dir_tmp/cia/$title/$title.cia $dir_games/$title_rename-$title.cia;
-touch $dir_locales/$title.txt;
-echo "USA EN" > $dir_locales/$title.txt;
-cd $dir_locales;
-for f in * ; do mv -- "$f" "$(tr [:lower:] [:upper:] <<< "$f")" ; done
+  echo "Moving game file...";
+  mv -v $dir_tmp/cia/$title/$title.cia $dir_games/$title_rename-$title.cia;
+  touch $dir_locales/$title.txt;
+  echo "USA EN" > $dir_locales/$title.txt;
+  cd $dir_locales;
+  for f in * ; do mv -- "$f" "$(tr [:lower:] [:upper:] <<< "$f")" ; done;
+  ;;
+  2)
+  echo "";
+  echo -n "Enter Title: "
+  read title;
+  echo -n "Enter encrypted title key: ";
+  read key;
+  echo -n "Rename title: "
+  read title_rename;
+  echo "";
+
+  python $bin_funkeycia -title $title -key $key;
+
+  echo "Moving update file...";
+  mv -v $dir_tmp/cia/$title/$title.cia $dir_updates/$title_rename-$title.cia;
+  ;;
+  *)
+  echo "";
+  echo "Invalid choice!";
+  exit 1;
+  ;;
+esac
+
 echo "";
 echo "Finished! <(' '  )> <( ' ' )> <(  ' ')>";
